app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function()
{
	return View::make('index');
});
Route::get('/album', 'AlbumController@index');

// Tours
Route::model('tour', 'DuranDuranNetworks\App\Models\Tour');
Route::model('tour_date', 'DuranDuranNetworks\App\Models\TourDate');
Route::model('tour_geocode', 'DuranDuranNetworks\App\Models\TourGeocode');
Route::get( '/tour', array( 'as' => 'tour.home', 'uses' => 'TourController@map' ));
Route::get( '/tour/{tour?}', array( 'as' => 'tour.map', 'uses' => 'TourController@map' ));
Route::any( '/tour/marker/{id?}', array( 'as' => 'tour.marker', 'uses' => 'TourController@marker' ) );
Route::group( array( 'prefix' => 'admin', 'middleware' => 'auth' ), function () {
	Route::get( '/', array( 'as' => 'admin.home', 'uses' => 'Admin\HomeController@admin' ) );

	Route::get( '/tour/{tour}/delete', array( 'as' => 'admin.tour.delete', 'uses' => 'Admin\TourController@delete' ) );
	Route::resource('tour', 'Admin\TourController');

	Route::get( '/tour-date/{tour_date}/delete', array( 'as' => 'admin.tour-date.delete', 'uses' => 'Admin\TourDateController@delete' ) );
	Route::resource('tour-date', 'Admin\TourDateController');

	Route::get( '/tour-geocode/{tour_geocode}/delete', array( 'as' => 'admin.tour-geocode.delete', 'uses' => 'Admin\TourGeocodeController@delete' ) );
	Route::post( '/tour-geocode/lookup-location', array( 'as' => 'admin.tour-geocode.lookup', 'uses' => 'Admin\TourGeocodeController@lookup' ) );
	Route::resource('tour-geocode', 'Admin\TourGeocodeController');
} );

// Authentication
Route::get( '/auth/login', array( 'as' => 'auth.login', 'uses' => 'AuthController@getLogin') );
Route::post( '/auth/login', array( 'as' => 'auth.signin', 'uses' => 'AuthController@postLogin' ) );
Route::get( '/auth/logout', array( 'as' => 'auth.logout', 'uses' => 'AuthController@getLogout' ) );

app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	return View::make('index');
});
Route::get('/album', 'AlbumController@index');

// Tours
Route::model('tour', 'Tour');
Route::model('tour_date', 'TourDate');
Route::model('tour_geocode', 'TourGeocode');
Route::get( '/tour', array( 'as' => 'tour.home', 'uses' => 'TourController@map' ));
Route::get( '/tour/{tour?}', array( 'as' => 'tour.map', 'uses' => 'TourController@map' ));
Route::any( '/tour/marker/{id?}', array( 'as' => 'tour.marker', 'uses' => 'TourController@marker' ) );
Route::group( array( 'prefix' => 'admin' ), function () {
	Route::get( '/', array( 'as' => 'admin.home', 'uses' => 'HomeController@admin' ) );

	Route::get( '/tour/{tour}/delete', array( 'as' => 'admin.tour.delete', 'before' => 'auth', 'uses' => 'TourController@delete' ) );
	Route::resource('tour', 'TourController');

	Route::get( '/tour-date/{tour_date}/delete', array( 'as' => 'admin.tour-date.delete', 'before' => 'auth', 'uses' => 'TourDateController@delete' ) );
	Route::resource('tour-date', 'TourDateController');

	Route::get( '/tour-geocode/{tour_geocode}/delete', array( 'as' => 'admin.tour-geocode.delete', 'before' => 'auth', 'uses' => 'TourGeocodeController@delete' ) );
	Route::post( '/tour-geocode/lookup-location', array( 'as' => 'admin.tour-geocode.lookup', 'before' => 'auth|csrf', 'uses' => 'TourGeocodeController@lookup' ) );
	Route::resource('tour-geocode', 'TourGeocodeController');
} );

// Authentication
Route::get( '/login', array( 'as' => 'auth.login', 'uses' => 'AuthController@login') );
Route::get( '/logout', array( 'as' => 'auth.logout', 'uses' => 'AuthController@sign_out' ) );
Route::post( '/signin', array( 'as' => 'auth.signin', 'uses' => 'AuthController@sign_in' ) );

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function()
{
	return View::make('index');
});
Route::get('/album', 'AlbumController@index');

// Tours
Route::model('tour', 'App\Models\Tour');
Route::model('tour_date', 'App\Models\TourDate');
Route::model('tour_geocode', 'App\Models\TourGeocode');
Route::get( '/tour', array( 'as' => 'tour.home', 'uses' => 'TourController@map' ));
Route::get( '/tour/{tour?}', array( 'as' => 'tour.map', 'uses' => 'TourController@map' ));
Route::any( '/tour/marker/{id?}', array( 'as' => 'tour.marker', 'uses' => 'TourController@marker' ) );
Route::group( array( 'prefix' => 'admin', 'middleware' => 'auth' ), function () {
	Route::get( '/', array( 'as' => 'admin.home', 'uses' => 'Admin\HomeController@admin' ) );

	Route::get( '/tour/{tour}/delete', array( 'as' => 'tour.delete', 'uses' => 'Admin\TourController@delete' ) );
	Route::resource('tour', 'Admin\TourController');

	Route::get( '/tour-date/{tour_date}/delete', array( 'as' => 'tour-date.delete', 'uses' => 'Admin\TourDateController@delete' ) );
	Route::resource('tour-date', 'Admin\TourDateController');

	Route::get( '/tour-geocode/{tour_geocode}/delete', array( 'as' => 'tour-geocode.delete', 'uses' => 'Admin\TourGeocodeController@delete' ) );
	Route::post( '/tour-geocode/lookup-location', array( 'as' => 'tour-geocode.lookup', 'uses' => 'Admin\TourGeocodeController@lookup' ) );
	Route::resource('tour-geocode', 'Admin\TourGeocodeController');
} );

// Authentication
Auth::routes();

//Route::get( '/auth/login', array( 'as' => 'auth.login', 'uses' => 'AuthController@getLogin') );
//Route::post( '/auth/login', array( 'as' => 'auth.signin', 'uses' => 'AuthController@postLogin' ) );
//Route::get( '/auth/logout', array( 'as' => 'auth.logout', 'uses' => 'AuthController@getLogout' ) );
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin.blade.php
@extends('layout')

@section('page_title')
 &raquo; Administration
@stop

@section('section_head')
<h2>Administration</h2>
@stop

@section('section_label')

@stop

@section('seciton_sublabel')
@stop

@section('content')

<div class="col-md-12">
	<ul>
		<li><a href="{{ route( 'tour.index' ) }}">Tour map history</a></li>
		<li><a href="{{ route( 'tour-geocode.index' ) }}">Tour map locations</a></li>
	</ul>
</div>

@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layout')

@section('content')

@stop

resources/views/layout.blade.php
<!DOCTYPE html "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Duran Duran Networks
			@yield('page_title')
		</title>
		<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
		<meta name="viewport" content="width=device-width">
		<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
		<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="{{ VIGILANTMEDIA_CDN_BASE_URI }}/web/css/jquery.jcarousel.css" type="text/css" media="screen, projection" />
		<link rel="stylesheet" href="{{ VIGILANTMEDIA_CDN_BASE_URI }}/web/css/chosen.min.css" type="text/css" />
		<link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" type="text/css" />
		<link rel="stylesheet" href="/css/style.css" type="text/css" media="screen, projection" />
		<link rel="stylesheet" href="/css/skins/ddn/skin.css" type="text/css" media="screen, projection" />
		<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
		<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
		<script type="text/javascript" src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
		<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="{{ VIGILANTMEDIA_CDN_BASE_URI }}/web/js/jquery.jcarousel.pack.js"></script>
		<script type="text/javascript" src="{{ VIGILANTMEDIA_CDN_BASE_URI }}/web/js/jquery.mousewheel.js"></script>
		<script type="text/javascript" src="{{ VIGILANTMEDIA_CDN_BASE_URI }}/web/js/jquery.em.js"></script>
		<script type="text/javascript" src="{{ VIGILANTMEDIA_CDN_BASE_URI }}/web/js/jScrollPane.js"></script>
		<script type="text/javascript" src="{{ VIGILANTMEDIA_CDN_BASE_URI }}/web/js/chosen.jquery.min.js"></script>
	</head>
	<body>

		<div id="container" class="container">
			
			<div class="row">
				<div id="masthead" class="col-md-12">
					<h1 id="title"><a href="/">Duran Duran Networks</a></h1>
					<h2>Duran Duran on the Web 2.0</h2>
				</div>

				<div class="collapse navbar-collapse" id="main-nav">
					<ul class="nav navbar-nav">
                        <li><a href="/">Home</a></li>
						@guest
							<li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
						@else
							<li>
								<a class="dropdown-item" href="{{ route('logout') }}"
								   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
									{{ __('Logout') }}
								</a>

								<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
									@csrf
								</form>
							</li>
						@endguest
					</ul>
				</div>
			</div>
			
			<div id="content" class="row">

				<div class="col-md-12">
					@yield('section_head')

					@yield('section_label')

					@yield('section_sublabel')

					@if ( Session::get('message') != '' )
					<div class="alert alert-success alert-dismissable">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						{{ Session::get('message') }}
					</div>
					@endif

					@if ( Session::get('error') != '' )
					<div class="alert alert-danger alert-dismissable">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						{{ Session::get('error') }}
					</div>
					@endif

				</div>


				@yield('content')

				@yield('sidebar')
			</div>
		</div>

		<footer class="row">
			<div class="col-md-12">
			</div>
		</footer>

		<script type="text/javascript">
			var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
			document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
		</script>
		<script type="text/javascript">
			try {
				var pageTracker = _gat._getTracker("UA-7828220-5");
				pageTracker._trackPageview();
			} catch (err) {
			}
		</script>

	</body>
</html>