app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function()
{
	return View::make('index');
});
Route::get('/album', 'AlbumController@index');

// Tours
Route::model('tour', 'DuranDuranNetworks\App\Models\Tour');
Route::model('tour_date', 'DuranDuranNetworks\App\Models\TourDate');
Route::model('tour_geocode', 'DuranDuranNetworks\App\Models\TourGeocode');
Route::get( '/tour', array( 'as' => 'tour.home', 'uses' => 'TourController@map' ));
Route::get( '/tour/{tour?}', array( 'as' => 'tour.map', 'uses' => 'TourController@map' ));
Route::any( '/tour/marker/{id?}', array( 'as' => 'tour.marker', 'uses' => 'TourController@marker' ) );
Route::group( array( 'prefix' => 'admin', 'middleware' => 'auth' ), function () {
	Route::get( '/', array( 'as' => 'admin.home', 'uses' => 'Admin\HomeController@admin' ) );

	Route::get( '/tour/{tour}/delete', array( 'as' => 'admin.tour.delete', 'uses' => 'Admin\TourController@delete' ) );
	Route::resource('tour', 'Admin\TourController');

	Route::get( '/tour-date/{tour_date}/delete', array( 'as' => 'admin.tour-date.delete', 'uses' => 'Admin\TourDateController@delete' ) );
	Route::resource('tour-date', 'Admin\TourDateController');

	Route::get( '/tour-geocode/{tour_geocode}/delete', array( 'as' => 'admin.tour-geocode.delete', 'uses' => 'Admin\TourGeocodeController@delete' ) );
	Route::post( '/tour-geocode/lookup-location', array( 'as' => 'admin.tour-geocode.lookup', 'uses' => 'Admin\TourGeocodeController@lookup' ) );
	Route::resource('tour-geocode', 'Admin\TourGeocodeController');
} );

// Authentication
Route::get( '/auth/login', array( 'as' => 'auth.login', 'uses' => 'AuthController@getLogin') );
Route::post( '/auth/login', array( 'as' => 'auth.signin', 'uses' => 'AuthController@postLogin' ) );
Route::get( '/auth/logout', array( 'as' => 'auth.logout', 'uses' => 'AuthController@getLogout' ) );

app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	return View::make('index');
});
Route::get('/album', 'AlbumController@index');

// Tours
Route::model('tour', 'Tour');
Route::model('tour_date', 'TourDate');
Route::model('tour_geocode', 'TourGeocode');
Route::get( '/tour', array( 'as' => 'tour.home', 'uses' => 'TourController@map' ));
Route::get( '/tour/{tour?}', array( 'as' => 'tour.map', 'uses' => 'TourController@map' ));
Route::any( '/tour/marker/{id?}', array( 'as' => 'tour.marker', 'uses' => 'TourController@marker' ) );
Route::group( array( 'prefix' => 'admin' ), function () {
	Route::get( '/', array( 'as' => 'admin.home', 'uses' => 'HomeController@admin' ) );

	Route::get( '/tour/{tour}/delete', array( 'as' => 'admin.tour.delete', 'before' => 'auth', 'uses' => 'TourController@delete' ) );
	Route::resource('tour', 'TourController');

	Route::get( '/tour-date/{tour_date}/delete', array( 'as' => 'admin.tour-date.delete', 'before' => 'auth', 'uses' => 'TourDateController@delete' ) );
	Route::resource('tour-date', 'TourDateController');

	Route::get( '/tour-geocode/{tour_geocode}/delete', array( 'as' => 'admin.tour-geocode.delete', 'before' => 'auth', 'uses' => 'TourGeocodeController@delete' ) );
	Route::post( '/tour-geocode/lookup-location', array( 'as' => 'admin.tour-geocode.lookup', 'before' => 'auth|csrf', 'uses' => 'TourGeocodeController@lookup' ) );
	Route::resource('tour-geocode', 'TourGeocodeController');
} );

// Authentication
Route::get( '/login', array( 'as' => 'auth.login', 'uses' => 'AuthController@login') );
Route::get( '/logout', array( 'as' => 'auth.logout', 'uses' => 'AuthController@sign_out' ) );
Route::post( '/signin', array( 'as' => 'auth.signin', 'uses' => 'AuthController@sign_in' ) );

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function()
{
	return View::make('index');
});
Route::get('/album', 'AlbumController@index');

// Tours
Route::model('tour', 'App\Models\Tour');
Route::model('tour_date', 'App\Models\TourDate');
Route::model('tour_geocode', 'App\Models\TourGeocode');
Route::get( '/tour', array( 'as' => 'tour.home', 'uses' => 'TourController@map' ));
Route::get( '/tour/{tour?}', array( 'as' => 'tour.map', 'uses' => 'TourController@map' ));
Route::any( '/tour/marker/{id?}', array( 'as' => 'tour.marker', 'uses' => 'TourController@marker' ) );
Route::group( array( 'prefix' => 'admin', 'middleware' => 'auth' ), function () {
	Route::get( '/', array( 'as' => 'admin.home', 'uses' => 'Admin\HomeController@admin' ) );

	Route::get( '/tour/{tour}/delete', array( 'as' => 'tour.delete', 'uses' => 'Admin\TourController@delete' ) );
	Route::resource('tour', 'Admin\TourController');

	Route::get( '/tour-date/{tour_date}/delete', array( 'as' => 'tour-date.delete', 'uses' => 'Admin\TourDateController@delete' ) );
	Route::resource('tour-date', 'Admin\TourDateController');

	Route::get( '/tour-geocode/{tour_geocode}/delete', array( 'as' => 'tour-geocode.delete', 'uses' => 'Admin\TourGeocodeController@delete' ) );
	Route::post( '/tour-geocode/lookup-location', array( 'as' => 'tour-geocode.lookup', 'uses' => 'Admin\TourGeocodeController@lookup' ) );
	Route::resource('tour-geocode', 'Admin\TourGeocodeController');
} );

// Authentication
Auth::routes();

//Route::get( '/auth/login', array( 'as' => 'auth.login', 'uses' => 'AuthController@getLogin') );
//Route::post( '/auth/login', array( 'as' => 'auth.signin', 'uses' => 'AuthController@postLogin' ) );
//Route::get( '/auth/logout', array( 'as' => 'auth.logout', 'uses' => 'AuthController@getLogout' ) );
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Tour.php
<?php

/**
 * Tour
 *
 * @author Greg Bueno
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tour extends Model {
	
	protected $table = 'ddn_tours';
	protected $primaryKey = 'tour_id';
	protected $softDelete = true;
	protected $fillable = array(
		'tour_name',
	);
	protected $guarded = array(
		'tour_id',
	);
	
	public function dates()
	{
		return $this->hasMany('App\Models\TourDate', 'date_tour_id', 'tour_id');
	}
	
	public function geocodes()
	{
		return $this->hasManyThrough('App\Models\TourGeocode', 'TourDate', 'date_tour_id', 'geocode_id');
	}

}

app/Http/Controllers/Admin/TourController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Tour;
use App\Models\TourDate;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Redirect;

class TourController extends Controller {

	private $layout_variables = array();
	private $google_map_key = 'ABQIAAAAenOcDWY3GB5qVSPOQiBt_xRPto5laNqVxgk7rNaULMnh65830hSw2SmWLSmHjjpbku0UcRlTK_fhGQ';

	public function __construct() {
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$tours = Tour::all();

		$page_variables = array(
			'tours' => $tours,
		);

		$data = array_merge($page_variables, $this->layout_variables);
		return View::make('tour.index', $data);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$tour = new Tour;

		$page_variables = array(
			'tour' => $tour,
		);

		$data = array_merge($page_variables, $this->layout_variables);
		return View::make('tour.create', $data);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$id = new Tour;

		$fields = $id->getFillable();

		foreach ($fields as $field) {
			$id->{$field} = Input::get($field);
		}

		$result = $id->save();

		if ($result !== false) {
			return Redirect::route('tour.show', array('id' => $id->tour_id))->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('tour.index')->with('error', 'Your changes were not saved.');
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$chunks = $id->dates->chunk(10);
		$dates = $chunks[0];

		$page_variables = array(
			'tour' => $id,
			'chunks' => $chunks,
			'dates' => $dates,
		);

		$data = array_merge($page_variables, $this->layout_variables);
		return View::make('tour.show', $data);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$page_variables = array(
			'tour' => $id,
		);

		$data = array_merge($page_variables, $this->layout_variables);
		return View::make('tour.edit', $data);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$fields = $id->getFillable();

		foreach ($fields as $field) {
			$id->{$field} = Input::get($field);
		}

		$result = $id->save();

		if ($result !== false) {
			return Redirect::route('tour.show', array('id' => $id->tour_id))->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('tour.index')->with('error', 'Your changes were not saved.');
		}
	}


	public function delete($id) {

		$method_variables = array(
			'tour' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('tour.delete', $data);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$confirm = (boolean) Input::get('confirm');
		$tour_name = $id->tour_name;

		if ($confirm === true) {
			// Remove tour.
			$id->delete();
			return Redirect::route('tour.index')->with('message', $tour_name . ' was deleted.');
		} else {
			return Redirect::route('tour.show', array('id' => $id->tour_id))->with('error', $tour_name . ' was not deleted.');
		}
	}

}

app/Http/Controllers/TourController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tour;
use App\Models\TourDate;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Redirect;

class TourController extends Controller {

	private $layout_variables = array();

	public function __construct() {
	}

	public function map($id = null) {
		if ($id == null) {
			$id = Tour::find(1);
		}

		$tours = Tour::all();

		$dates = array();
		foreach ($id->dates as $date) {
			$dates[] = (object) array(
				'date_id' => $date->date_id,
				'geocode_lat' => $date->geocode->geocode_lat,
				'geocode_lon' => $date->geocode->geocode_lon,
			);
		}

		$page_variables = array(
			'tours' => $tours,
			'tour' => $id,
			'dates' => json_encode($dates),
			'google_map_key' => GOOGLE_MAPS_API_KEY,
		);

		$data = array_merge($page_variables, $this->layout_variables);
		return View::make('tour.map', $data);
	}

	public function marker($id) {
		$tour_date = TourDate::find($id);

		$data = array(
			'tour_date' => $tour_date,
		);

		return View::make('tour.marker', $data);
	}
}

resources/views/tour/date/_form.blade.php
@extends('layout')

@section('content')

<div class="form-group">
	{!! Form::label( 'date_tour_id', 'Tour:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::select( 'date_tour_id', $tours, $date->date_tour_id, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'date_geocode_id', 'Location:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::select( 'date_geocode_id', $geocodes, $date->date_geocode_id, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'date_tour_date', 'Date:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'date_tour_date', date('Y-m-d', strtotime($date->date_tour_date) ), array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	<div class="col-sm-10 col-sm-offset-2">
		{!! Form::submit( 'Save', array( 'class' => 'btn btn-primary' ) ) !!}
	</div>
</div>

<script type="text/javascript">
	(function ($) {
		$('#date_tour_id').chosen();
		$('#date_geocode_id').chosen();

		$('#date_tour_date').datepicker({
			dateFormat: 'yy-mm-dd'
		});
	})(jQuery);
</script>

@stop

resources/views/tour/date/create.blade.php
@extends('tour.date._form')

@section('page_title')
 &raquo; Administration
 &raquo; Tours
 &raquo; Add a date
@stop

@section('section_head')
<h2>Tour History</h2>
@stop

@section('section_label')
<h3>Add a date</h3>
@stop

@section('section_sublabel')
@stop

@section('content')
<div class="col-md-8">
	{!! Form::model( $date, array( 'route' => 'tour-date.store', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post' ) ) !!}
	@parent
	{!! Form::close() !!}
</div>
@stop

@section('sidebar')
<div class="col-md-4">

</div>
@stop

resources/views/tour/date/delete.blade.php
@extends('layout')

@section('page_title')
 &raquo; Tour History Map
 &raquo; {{ $date->tour->tour_name }}
 &raquo; {{ $date->geocode->geocode_location }}: {{ date('Y-m-d', strtotime( $date->date_tour_date )) }}
 &raquo; Delete
@stop

@section('section_head')
<hgroup>
	<h2>
		Tours
		<small>{{ $date->tour->tour_name }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>
	Delete
	<small>{{ $date->geocode->geocode_location }}: {{ date('Y-m-d', strtotime( $date->date_tour_date )) }}</small>
</h3>
@stop

@section('content')
<div class="col-md-8">
	<p>
		You are about to delete <strong><em>{{ $date->geocode->geocode_location }}: {{ date('Y-m-d', strtotime( $date->date_tour_date )) }}</em></strong> from the database.
	</p>

	<p>
		Are you sure you want to do this?
	</p>

	{!! Form::model( $date, array( 'route' => array( 'tour-date.destroy', $date->date_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'delete' ) ) !!}

	<div class="form-group">
		<div class="col-sm-12">
			<div class="radio">
				<label>
					{!! Form::radio('confirm', '1') !!} Yes, I want to delete {{ $date->geocode->geocode_location }}: {{ date('Y-m-d', strtotime( $date->date_tour_date )) }}.
				</label>
			</div>
			<div class="radio">
				<label>
					{!! Form::radio('confirm', '0') !!} No, I don't want to delete {{ $date->geocode->geocode_location }}: {{ date('Y-m-d', strtotime( $date->date_tour_date )) }}.
				</label>
			</div>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-12">
			{!! Form::submit('Confirm', array( 'class' => 'btn btn-danger' )) !!}
		</div>
	</div>


	{!! Form::close() !!}
</div>


@stop

resources/views/tour/date/edit.blade.php
@extends('tour.date._form')

@section('page_title')
 &raquo; Administration
 &raquo; Tours
 &raquo; {{ $date->tour->tour_name }}
 &raquo; {{ $date->geocode->geocode_location }}: {{ date('Y-m-d', strtotime( $date->date_tour_date )) }}
 &raquo; Edit
@stop

@section('section_head')
<h2>
	Tour History
	<small>{{ $date->tour->tour_name}}</small>
</h2>
@stop

@section('section_label')
<h3>
	Edit
	<small>{{ $date->geocode->geocode_location }}: {{ date('Y-m-d', strtotime( $date->date_tour_date )) }}</small>
</h3>
@stop

@section('section_sublabel')
@stop

@section('content')
<div class="col-md-8">
	{!! Form::model( $date, array( 'route' => array('tour-date.update', $date->date_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'put' ) ) !!}
	@parent
	{!! Form::close() !!}
</div>
@stop

@section('sidebar')
<div class="col-md-4">

</div>
@stop

resources/views/tour/date/index.blade.php
@extends('layout')

@section('page_title')
 &raquo; Administration
 &raquo; Tours
 &raquo; Dates
@stop

@section('section_head')
<h2>Tour History</h2>
@stop

@section('section_label')
<h3>Tour Dates</h3>
@stop

@section('section_sublabel')
@stop

@section('content')
<div class="col-md-8">

	<ul class="list-inline">
		<li><a href="{{ route( 'tour-date.create', [ 'tour' => $tour ] ) }}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add a date</a></li>
	</ul>

	@if (count($dates) > 0)
	<ul class="list-unstyled">
		@foreach ($dates as $date)
		<li>
			<ul class="list-inline">
				<li><a href="{{ route( 'tour-date.edit', array( 'id' => $date->date_id ) ) }}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-pencil"></span> <span class="sr-only">Edit</span></a></li>
				<li><a href="{{ route( 'tour-date.delete', array( 'id' => $date->date_id ) ) }}" class="btn btn-warning btn-xs"><span class="glyphicon glyphicon-remove"></span> <span class="sr-only">Remove</span></a></li>
				<li><a href="{{ route( 'tour-date.show', array( 'id' => $date->date_id ) ) }}">{{ date('Y-m-d', strtotime($date->date_tour_date)) }}: {{ $date->geocode->geocode_location }}</a></li>
			</ul>
		</li>
		@endforeach
	</ul>
	@endif

    {!! $dates->appends( [ 'tour' => $tour ])->render() !!}
</div>
@stop

@section('sidebar')
<div class="col-md-4">

</div>
@stop

resources/views/tour/date/show.blade.php
@extends('layout')

@section('page_title')
 &raquo; Administration
 &raquo; Tours
 &raquo; {{ $date->tour->tour_name }}
 &raquo; {{ $date->geocode->geocode_location }}: {{ date('Y-m-d', strtotime( $date->date_tour_date )) }}
@stop

@section('section_head')
<h2>Tour History</h2>
@stop

@section('section_label')
<h3>
	Tours
	<small>{{ $date->tour->tour_name }}</small>
</h3>
@stop

@section('section_sublabel')
<h3>
	Date
	<small>{{ $date->geocode->geocode_location }}: {{ date('Y-m-d', strtotime( $date->date_tour_date )) }}</small>
</h3>
@stop

@section('content')
<div class="col-md-8">

	<ul class="list-inline">
		<li><a href="{{ route( 'tour-date.edit', array( 'id' => $date->date_id ) ) }}" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span> Edit</a></li>
		<li><a href="{{ route( 'tour-date.delete', array( 'id' => $date->date_id ) ) }}" class="btn btn-warning"><span class="glyphicon glyphicon-remove"></span> Delete</a></li>
	</ul>

    <div class="row">
        <div class="col-xs-2">
            <label>Tour name:</label>
        </div>
        <div class="col-xs-10">
            {{ $date->tour->tour_name }}
        </div>
    </div>

    <div class="row">
        <div class="col-xs-2">
            <label>Location:</label>
        </div>
        <div class="col-xs-10">
            <a href="{{ route( 'tour-geocode.show', array( $date->geocode->geocode_id ) ) }}">{{ $date->geocode->geocode_location }}</a>,
            @if (!empty($date->geocode->geocode_city))
                {{ $date->geocode->geocode_city }},
            @endif
            @if (!empty($date->geocode->geocode_state))
                {{ $date->geocode->geocode_state }},
            @endif
            @if (!empty($date->geocode->country->country_name))
                {{ $date->geocode->country->country_name }}
            @endif
        </div>
    </div>

    <div class="row">
        <div class="col-xs-2">
            <label>Location:</label>
        </div>
        <div class="col-xs-10">
            <a href="{{ route( 'tour-geocode.show', array( $date->geocode->geocode_id ) ) }}">{{ $date->geocode->geocode_location }}</a>,
            @if (!empty($date->geocode->geocode_city))
                {{ $date->geocode->geocode_city }},
            @endif
            @if (!empty($date->geocode->geocode_state))
                {{ $date->geocode->geocode_state }},
            @endif
            @if (!empty($date->geocode->country->country_name))
                {{ $date->geocode->country->country_name }}
            @endif
        </div>
    </div>

    <div class="row">
        <div class="col-xs-2">
            <label>Date:</label>
        </div>
        <div class="col-xs-10">
            {{ date('Y-m-d', strtotime($date->date_tour_date) )  }}
        </div>
    </div>

</div>
@stop

@section('sidebar')
<div class="col-md-4">

</div>
@stop