app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function()
{
	return View::make('index');
});
Route::get('/album', 'AlbumController@index');

// Tours
Route::model('tour', 'DuranDuranNetworks\App\Models\Tour');
Route::model('tour_date', 'DuranDuranNetworks\App\Models\TourDate');
Route::model('tour_geocode', 'DuranDuranNetworks\App\Models\TourGeocode');
Route::get( '/tour', array( 'as' => 'tour.home', 'uses' => 'TourController@map' ));
Route::get( '/tour/{tour?}', array( 'as' => 'tour.map', 'uses' => 'TourController@map' ));
Route::any( '/tour/marker/{id?}', array( 'as' => 'tour.marker', 'uses' => 'TourController@marker' ) );
Route::group( array( 'prefix' => 'admin', 'middleware' => 'auth' ), function () {
	Route::get( '/', array( 'as' => 'admin.home', 'uses' => 'Admin\HomeController@admin' ) );

	Route::get( '/tour/{tour}/delete', array( 'as' => 'admin.tour.delete', 'uses' => 'Admin\TourController@delete' ) );
	Route::resource('tour', 'Admin\TourController');

	Route::get( '/tour-date/{tour_date}/delete', array( 'as' => 'admin.tour-date.delete', 'uses' => 'Admin\TourDateController@delete' ) );
	Route::resource('tour-date', 'Admin\TourDateController');

	Route::get( '/tour-geocode/{tour_geocode}/delete', array( 'as' => 'admin.tour-geocode.delete', 'uses' => 'Admin\TourGeocodeController@delete' ) );
	Route::post( '/tour-geocode/lookup-location', array( 'as' => 'admin.tour-geocode.lookup', 'uses' => 'Admin\TourGeocodeController@lookup' ) );
	Route::resource('tour-geocode', 'Admin\TourGeocodeController');
} );

// Authentication
Route::get( '/auth/login', array( 'as' => 'auth.login', 'uses' => 'AuthController@getLogin') );
Route::post( '/auth/login', array( 'as' => 'auth.signin', 'uses' => 'AuthController@postLogin' ) );
Route::get( '/auth/logout', array( 'as' => 'auth.logout', 'uses' => 'AuthController@getLogout' ) );

app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	return View::make('index');
});
Route::get('/album', 'AlbumController@index');

// Tours
Route::model('tour', 'Tour');
Route::model('tour_date', 'TourDate');
Route::model('tour_geocode', 'TourGeocode');
Route::get( '/tour', array( 'as' => 'tour.home', 'uses' => 'TourController@map' ));
Route::get( '/tour/{tour?}', array( 'as' => 'tour.map', 'uses' => 'TourController@map' ));
Route::any( '/tour/marker/{id?}', array( 'as' => 'tour.marker', 'uses' => 'TourController@marker' ) );
Route::group( array( 'prefix' => 'admin' ), function () {
	Route::get( '/', array( 'as' => 'admin.home', 'uses' => 'HomeController@admin' ) );

	Route::get( '/tour/{tour}/delete', array( 'as' => 'admin.tour.delete', 'before' => 'auth', 'uses' => 'TourController@delete' ) );
	Route::resource('tour', 'TourController');

	Route::get( '/tour-date/{tour_date}/delete', array( 'as' => 'admin.tour-date.delete', 'before' => 'auth', 'uses' => 'TourDateController@delete' ) );
	Route::resource('tour-date', 'TourDateController');

	Route::get( '/tour-geocode/{tour_geocode}/delete', array( 'as' => 'admin.tour-geocode.delete', 'before' => 'auth', 'uses' => 'TourGeocodeController@delete' ) );
	Route::post( '/tour-geocode/lookup-location', array( 'as' => 'admin.tour-geocode.lookup', 'before' => 'auth|csrf', 'uses' => 'TourGeocodeController@lookup' ) );
	Route::resource('tour-geocode', 'TourGeocodeController');
} );

// Authentication
Route::get( '/login', array( 'as' => 'auth.login', 'uses' => 'AuthController@login') );
Route::get( '/logout', array( 'as' => 'auth.logout', 'uses' => 'AuthController@sign_out' ) );
Route::post( '/signin', array( 'as' => 'auth.signin', 'uses' => 'AuthController@sign_in' ) );

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function()
{
	return View::make('index');
});
Route::get('/album', 'AlbumController@index');

// Tours
Route::model('tour', 'App\Models\Tour');
Route::model('tour_date', 'App\Models\TourDate');
Route::model('tour_geocode', 'App\Models\TourGeocode');
Route::get( '/tour', array( 'as' => 'tour.home', 'uses' => 'TourController@map' ));
Route::get( '/tour/{tour?}', array( 'as' => 'tour.map', 'uses' => 'TourController@map' ));
Route::any( '/tour/marker/{id?}', array( 'as' => 'tour.marker', 'uses' => 'TourController@marker' ) );
Route::group( array( 'prefix' => 'admin', 'middleware' => 'auth' ), function () {
	Route::get( '/', array( 'as' => 'admin.home', 'uses' => 'Admin\HomeController@admin' ) );

	Route::get( '/tour/{tour}/delete', array( 'as' => 'tour.delete', 'uses' => 'Admin\TourController@delete' ) );
	Route::resource('tour', 'Admin\TourController');

	Route::get( '/tour-date/{tour_date}/delete', array( 'as' => 'tour-date.delete', 'uses' => 'Admin\TourDateController@delete' ) );
	Route::resource('tour-date', 'Admin\TourDateController');

	Route::get( '/tour-geocode/{tour_geocode}/delete', array( 'as' => 'tour-geocode.delete', 'uses' => 'Admin\TourGeocodeController@delete' ) );
	Route::post( '/tour-geocode/lookup-location', array( 'as' => 'tour-geocode.lookup', 'uses' => 'Admin\TourGeocodeController@lookup' ) );
	Route::resource('tour-geocode', 'Admin\TourGeocodeController');
} );

// Authentication
Auth::routes();

//Route::get( '/auth/login', array( 'as' => 'auth.login', 'uses' => 'AuthController@getLogin') );
//Route::post( '/auth/login', array( 'as' => 'auth.signin', 'uses' => 'AuthController@postLogin' ) );
//Route::get( '/auth/logout', array( 'as' => 'auth.logout', 'uses' => 'AuthController@getLogout' ) );
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Tour.php
<?php

/**
 * Tour
 *
 * @author Greg Bueno
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tour extends Model {
	
	protected $table = 'ddn_tours';
	protected $primaryKey = 'tour_id';
	protected $softDelete = true;
	protected $fillable = array(
		'tour_name',
	);
	protected $guarded = array(
		'tour_id',
	);
	
	public function dates()
	{
		return $this->hasMany('App\Models\TourDate', 'date_tour_id', 'tour_id');
	}
	
	public function geocodes()
	{
		return $this->hasManyThrough('App\Models\TourGeocode', 'TourDate', 'date_tour_id', 'geocode_id');
	}

}

app/Http/Controllers/Admin/TourController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Tour;
use App\Models\TourDate;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Redirect;

class TourController extends Controller {

	private $layout_variables = array();
	private $google_map_key = 'ABQIAAAAenOcDWY3GB5qVSPOQiBt_xRPto5laNqVxgk7rNaULMnh65830hSw2SmWLSmHjjpbku0UcRlTK_fhGQ';

	public function __construct() {
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$tours = Tour::all();

		$page_variables = array(
			'tours' => $tours,
		);

		$data = array_merge($page_variables, $this->layout_variables);
		return View::make('tour.index', $data);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$tour = new Tour;

		$page_variables = array(
			'tour' => $tour,
		);

		$data = array_merge($page_variables, $this->layout_variables);
		return View::make('tour.create', $data);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$id = new Tour;

		$fields = $id->getFillable();

		foreach ($fields as $field) {
			$id->{$field} = Input::get($field);
		}

		$result = $id->save();

		if ($result !== false) {
			return Redirect::route('tour.show', array('id' => $id->tour_id))->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('tour.index')->with('error', 'Your changes were not saved.');
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$chunks = $id->dates->chunk(10);
		$dates = $chunks[0];

		$page_variables = array(
			'tour' => $id,
			'chunks' => $chunks,
			'dates' => $dates,
		);

		$data = array_merge($page_variables, $this->layout_variables);
		return View::make('tour.show', $data);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$page_variables = array(
			'tour' => $id,
		);

		$data = array_merge($page_variables, $this->layout_variables);
		return View::make('tour.edit', $data);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$fields = $id->getFillable();

		foreach ($fields as $field) {
			$id->{$field} = Input::get($field);
		}

		$result = $id->save();

		if ($result !== false) {
			return Redirect::route('tour.show', array('id' => $id->tour_id))->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('tour.index')->with('error', 'Your changes were not saved.');
		}
	}


	public function delete($id) {

		$method_variables = array(
			'tour' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('tour.delete', $data);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$confirm = (boolean) Input::get('confirm');
		$tour_name = $id->tour_name;

		if ($confirm === true) {
			// Remove tour.
			$id->delete();
			return Redirect::route('tour.index')->with('message', $tour_name . ' was deleted.');
		} else {
			return Redirect::route('tour.show', array('id' => $id->tour_id))->with('error', $tour_name . ' was not deleted.');
		}
	}

}

app/Http/Controllers/TourController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tour;
use App\Models\TourDate;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Redirect;

class TourController extends Controller {

	private $layout_variables = array();

	public function __construct() {
	}

	public function map($id = null) {
		if ($id == null) {
			$id = Tour::find(1);
		}

		$tours = Tour::all();

		$dates = array();
		foreach ($id->dates as $date) {
			$dates[] = (object) array(
				'date_id' => $date->date_id,
				'geocode_lat' => $date->geocode->geocode_lat,
				'geocode_lon' => $date->geocode->geocode_lon,
			);
		}

		$page_variables = array(
			'tours' => $tours,
			'tour' => $id,
			'dates' => json_encode($dates),
			'google_map_key' => GOOGLE_MAPS_API_KEY,
		);

		$data = array_merge($page_variables, $this->layout_variables);
		return View::make('tour.map', $data);
	}

	public function marker($id) {
		$tour_date = TourDate::find($id);

		$data = array(
			'tour_date' => $tour_date,
		);

		return View::make('tour.marker', $data);
	}
}

resources/views/tour/geocode/_form.blade.php
@extends('layout')

@section('content')

<div class="form-group">
	{!! Form::label( 'geocode_location', 'Location:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'geocode_location', $geocode->geocode_location, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'geocode_address', 'Address:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'geocode_address', $geocode->geocode_address, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'geocode_city', 'City:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'geocode_city', $geocode->geocode_city, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'geocode_state', 'State:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'geocode_state', $geocode->geocode_state, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'geocode_country_id', 'Country:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::select( 'geocode_country_id', $countries, $geocode->geocode_country_id, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	<div class="col-sm-10 col-sm-offset-2">
		{!! Form::button( 'Look up', array( 'class' => 'btn btn-default btn-sm', 'id' => 'lookup-location' ) ) !!}
	</div>
</div>
<div class="form-group">
	{!! Form::label( 'geocode_lon', 'Longitude:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'geocode_lon', $geocode->geocode_lon, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'geocode_lat', 'Latitude:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'geocode_lat', $geocode->geocode_lat, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	<div class="col-sm-10 col-sm-offset-2">
		{!! Form::submit( 'Save', array( 'class' => 'btn btn-primary' ) ) !!}
	</div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAPS_API_KEY }}" type="text/javascript"></script>
<script type="text/javascript">
	(function ($) {
		$(function () {
			$('#geocode_country_id').chosen();

			var latLon = new google.maps.LatLng({{ !empty($geocode->geocode_lat) ? $geocode->geocode_lat : 0 }} , {{ !empty($geocode->geocode_lon) ? $geocode->geocode_lon : 0 }});
			var mapOptions = {
				center: latLon,
				zoom: 16
			};
			var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
			var marker = new google.maps.Marker({
				position: latLon,
				map: map,
				title: '{{ $geocode->geocode_location }}'
			});

			$('#lookup-location').click(function () {
				var url = '{{ route("tour-geocode.lookup") }}';
				var data = {
					'geocode_location': $('#geocode_location').val(),
					'geocode_address': $('#geocode_address').val(),
					'geocode_city': $('#geocode_city').val(),
					'geocode_state': $('#geocode_state').val(),
					'geocode_country': $('#geocode_country_id').val(),
					'_token': $('input[name=_token]').val()
				};
				$('body').css('cursor', 'progress');
				$.post(url, data, function(response) {
					var map_data = $.parseJSON(response);
					var lng = map_data.results[0].geometry.location.lng;
					var lat = map_data.results[0].geometry.location.lat;

					$('#geocode_lon').val(lng);
					$('#geocode_lat').val(lat);

					var newLatLon = new google.maps.LatLng(lat, lng);
					map.setCenter(newLatLon);
					marker.setPosition(newLatLon);
					marker.setTitle($('#geocode_location').val());

					$('body').css('cursor', 'default');
				});
			});
		});

	})(jQuery);
</script>

@stop

@section('sidebar')

<h4>Preview</h4>

<div id="map-canvas" style="width: 100%; height: 300px;">
	<p>Look up coordinates to see a preview.</p>
</div>

@stop

resources/views/tour/geocode/create.blade.php
@extends('tour.geocode._form')

@section('page_title')
 &raquo; Administration
 &raquo; Tours
 &raquo; Add a location
@stop

@section('section_head')
<h2>Tour History</h2>
@stop

@section('section_label')
<h3>Add a location</h3>
@stop

@section('section_sublabel')
@stop

@section('content')
<div class="col-md-8">
	{!! Form::model( $geocode, array( 'route' => 'tour-geocode.store', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post' ) ) !!}
	@parent
	{!! Form::close() !!}
</div>
@stop

@section('sidebar')
<div class="col-md-4">
@parent
</div>
@stop

resources/views/tour/geocode/delete.blade.php
@extends('layout')

@section('page_title')
 &raquo; Tour History Map
 &raquo; {{ $geocode->geocode_location }}
 &raquo; Delete
@stop

@section('section_head')
<hgroup>
	<h2>
		Tours
		<small>{{ $geocode->geocode_location }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>Delete</h3>
@stop

@section('content')
<div class="col-md-8">
	<p>
		You are about to delete <strong><em>{{ $geocode->geocode_location }}</em></strong> from the database.
	</p>

	<p>
		Are you sure you want to do this?
	</p>

	{!! Form::model( $geocode, array( 'route' => array( 'tour-geocode.destroy', $geocode->geocode_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'delete' ) ) !!}

	<div class="form-group">
		<div class="col-sm-12">
			<div class="radio">
				<label>
					{!! Form::radio('confirm', '1') !!} Yes, I want to delete {{ $geocode->geocode_location }}.
				</label>
			</div>
			<div class="radio">
				<label>
					{!! Form::radio('confirm', '0') !!} No, I don't want to delete {{ $geocode->geocode_location }}.
				</label>
			</div>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-12">
			{!! Form::submit('Confirm', array( 'class' => 'btn btn-danger' )) !!}
		</div>
	</div>


	{!! Form::close() !!}
</div>


@stop

resources/views/tour/geocode/edit.blade.php
@extends('tour.geocode._form')

@section('page_title')
 &raquo; Administration
 &raquo; Tours
 &raquo; {{ $geocode->geocode_location }}
 &raquo; Edit
@stop

@section('section_head')
<h2>
	Tour History
	<small>{{ $geocode->geocode_location }}</small>
</h2>
@stop

@section('section_label')
<h3>Edit</h3>
@stop

@section('section_sublabel')
@stop

@section('content')
<div class="col-md-8">
	{!! Form::model( $geocode, array( 'route' => array('tour-geocode.update', $geocode->geocode_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'put' ) ) !!}
	@parent
	{!! Form::close() !!}
</div>
@stop

@section('sidebar')
<div class="col-md-4">
	@parent
</div>
@stop

resources/views/tour/geocode/index.blade.php
@extends('layout')

@section('page_title')
 &raquo; Administration
 &raquo; Tours
 &raquo; Geocodes
@stop

@section('section_head')
<h2>Tour History</h2>
@stop

@section('section_label')
<h3>Geocodes</h3>
@stop

@section('section_sublabel')
@stop

@section('content')
<div class="col-md-8">

	<ul class="list-inline">
		<li><a href="{{ route( 'tour-geocode.create' ) }}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add a location</a></li>
	</ul>

	@if (count($geocodes) > 0)
	<ul class="list-unstyled">
		@foreach ($geocodes as $geocode)
		<li>
			<ul class="list-inline">
				<li><a href="{{ route( 'tour-geocode.edit', array( 'id' => $geocode->geocode_id ) ) }}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-pencil"></span> <span class="sr-only">Edit</span></a></li>
				<li><a href="{{ route( 'tour-geocode.delete', array( 'id' => $geocode->geocode_id ) ) }}" class="btn btn-warning btn-xs"><span class="glyphicon glyphicon-remove"></span> <span class="sr-only">Remove</span></a></li>
				<li>
					<a href="{{ route( 'tour-geocode.show', array( 'id' => $geocode->geocode_id ) ) }}">{{ $geocode->geocode_location }}</a>,
					@if (!empty( $geocode->geocode_city ))
					{{ $geocode->geocode_city }},
					@endif
					@if (!empty( $geocode->geocode_state ))
					{{ $geocode->geocode_state }},
					@endif
					@if (!empty( $geocode->country->country_name ))
					{{ $geocode->country->country_name }}
					@endif
				</li>
			</ul>
		</li>
		@endforeach
	</ul>
	@endif

    {!! $geocodes->render() !!}
</div>
@stop

@section('sidebar')
<div class="col-md-4">

</div>
@stop

resources/views/tour/geocode/show.blade.php
@extends('layout')

@section('page_title')
 &raquo; Administration
 &raquo; Tours
 &raquo; {{ $geocode->geocode_location }}
@stop

@section('section_head')
<h2>Tour History</h2>
@stop

@section('section_label')
<h3>
	Tours
	<small>{{ $geocode->geocode_location }}</small>
</h3>
@stop

@section('section_sublabel')
<h3>
	Location
</h3>
@stop

@section('content')
<div class="col-md-8">

	<ul class="list-inline">
		<li><a href="{{ route( 'tour-geocode.edit', array( 'id' => $geocode->geocode_id ) ) }}" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span> Edit</a></li>
		<li><a href="{{ route( 'tour-geocode.delete', array( 'id' => $geocode->geocode_id ) ) }}" class="btn btn-warning"><span class="glyphicon glyphicon-remove"></span> Delete</a></li>
	</ul>

    <div class="row">
        <div class="col-md-2">
            <label>Location:</label>
        </div>
        <div class="col-md-10">
            {{ $geocode->geocode_location }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <label>Address:</label>
        </div>
        <div class="col-md-10">
            {{ $geocode->geocode_address }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <label>City:</label>
        </div>
        <div class="col-md-10">
            {{ $geocode->geocode_city }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <label>State/Province:</label>
        </div>
        <div class="col-md-10">
            {{ $geocode->geocode_state }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <label>Country:</label>
        </div>
        <div class="col-md-10">
            {{ $geocode->country->country_name }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <label>Longitude:</label>
        </div>
        <div class="col-md-10">
            {{ $geocode->geocode_lon }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <label>Latitude:</label>
        </div>
        <div class="col-md-10">
            {{ $geocode->geocode_lat }}
        </div>
    </div>


</div>
@stop

@section('sidebar')
<script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAPS_API_KEY }}" type="text/javascript"></script>
<script type="text/javascript">
	(function ($) {
		$(function () {
			$('#geocode_country_id').chosen();

			var latLon = new google.maps.LatLng({{ !empty($geocode->geocode_lat) ? $geocode->geocode_lat : 0 }} , {{ !empty($geocode->geocode_lon) ? $geocode->geocode_lon : 0 }});
			var mapOptions = {
				center: latLon,
				zoom: 16
			};
			var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
			var marker = new google.maps.Marker({
				position: latLon,
				map: map,
				title: '{{ $geocode->geocode_location }}'
			});

			$('#lookup-location').click(function () {
				var url = '{{ route("tour-geocode.lookup") }}';
				var data = {
					'geocode_location': $('#geocode_location').val(),
					'geocode_address': $('#geocode_address').val(),
					'geocode_city': $('#geocode_city').val(),
					'geocode_state': $('#geocode_state').val(),
					'geocode_country': $('#geocode_country_id').val(),
					'_token': $('input[name=_token]').val()
				};
				$('body').css('cursor', 'progress');
				$.post(url, data, function(response) {
					var map_data = $.parseJSON(response);
					var lng = map_data.results[0].geometry.location.lng;
					var lat = map_data.results[0].geometry.location.lat;

					$('#geocode_lon').val(lng);
					$('#geocode_lat').val(lat);

					var newLatLon = new google.maps.LatLng(lat, lng);
					map.setCenter(newLatLon);
					marker.setPosition(newLatLon);
					marker.setTitle($('#geocode_location').val());

					$('body').css('cursor', 'default');
				});
			});
		});
	})(jQuery);
</script>

<div class="col-md-4">
	<h4>Preview</h4>

	<div id="map-canvas" style="width: 100%; height: 300px;">
		<p>Set coordinates to see a preview.</p>
	</div>

</div>
@stop